### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by d-a-v** [nadjieb/cpp-mjpeg-streamer#32]
Thanks for this library, I am successfully using it with a thermal camera !

I have two questions: In the example's main loop,
- How can I know whether a remote client is connected 
- When no client is connected, how can I wait for a new incoming new client while waiting in a blocking state
(like when calling `poll()` with a negative timeout)

The goal is to be able to shut down the camera until new clients connects, and wait quietly until then.

**Comment by ricardojlrufino** [comment]
// only capture if exist client..
    	if(!streamer.hasClient("/bgr")){
    		std::this_thread::sleep_for(std::chrono::milliseconds(250));
    		continue;
    	}

**Comment by kamalnadjieb** [comment]
Hi @d-a-v , sorry for the late reply.

Currently the `nadjieb::MJPEGStreamer` class only have a public method to check if a topic has client(s) connected. I need to review the overall design goal to decide whether the class need such method to be implemented. For now, I think you can modify @ricardojlrufino implementation above to suite your need. Thank you.

Regards,

Kamal
