### ISSUE TITLE
Frame Rate 

### ISSUE THREAD

**Issue by somdats** [nadjieb/cpp-mjpeg-streamer#33]
@kamalnadjieb 
Thanks for your wonderful repo.
I have a question regarding the frame rate.
Is it possible to set the frame rate for the HTTP streaming?

**Comment by kamalnadjieb** [comment]
Hi @somdats , thank you for the compliment.

I need to review the overall design to decide whether to limit frame rate is the responsibility of the library or it is the user's responsibility before enqueue it to the streamer. The point is I want to make this library's implementation and scope as minimum as possible. Thank you.

Regards,

Kamal
