### ISSUE TITLE
Snapshot Feature

### ISSUE THREAD

**Issue by ricardojlrufino** [nadjieb/cpp-mjpeg-streamer#34]
I would like to include an option to take a snapshot, instead of streaming.
It's possible ?

**Comment by kamalnadjieb** [comment]
Hi @ricardojlrufino ,

I need to review the overall design to decide whether such feature is needed in the library. The point is I want to make this library's implementation and scope as minimum as possible. But, feel free if you want to contribute. Thank you.

Regards,

Kamal
