### ISSUE TITLE
Two stream in same port

### ISSUE THREAD

**Issue by DiagnozHub** [nadjieb/cpp-mjpeg-streamer#35]
Hello, Can I send stream from two cameras into same port (8081 for example), but with different paths (publish id) ?

localhost:8081/uid1
localhost:8081/uid2

**Comment by CYL-Oscar** [comment]
Yes! You can refer to the example and modify it.

for example :
 streamer.start(8080);
///////////////////////
 streamer.publish("/uid1", std::string(buff_bgr.begin(), buff_bgr.end()));
 streamer.publish("/uid2", std::string(buff_bgr.begin(), buff_bgr.end()));
